import { Component,Input,OnInit } from '@angular/core';
import { CommonModule } from '@angular/common';
import { FormsModule } from '@angular/forms';
import { HttpClient } from '@angular/common/http';

@Component({selector:'app-comparison-sleep',standalone:true,imports:[CommonModule,FormsModule],
 template:`<section class="panel"><h2>Sueño por épocas etiquetadas</h2><p>Importa etiquetas explícitas de dispositivo y referencia. No se estiman etapas a partir de FC/HRV. Cada época requiere inicio con zona horaria y duración común de 30 o 60 s.</p><p role="alert">{{message}}</p>
 <fieldset [disabled]="busy"><details><summary>Importar grabación JSON</summary><label>Archivo<input type="file" accept=".json,application/json" (change)="readFile($event)"></label><label>Dispositivo (opcional para referencia)<select [(ngModel)]="deviceId"><option value="">Referencia externa</option><option *ngFor="let d of devices" [value]="d.id">{{d.name}}</option></select></label><textarea [(ngModel)]="sourceJson" rows="15" aria-label="Grabación de sueño JSON"></textarea>
 <p>Campos: nombre, participante seudonimizado, versión de mapping, correspondencia de etiquetas y épocas. Para FOUR_STAGE usa WAKE/LIGHT/DEEP/REM; para FIVE_STAGE, WAKE/N1/N2/N3/REM. Etiquetas sin mapping quedan sin dato.</p><button (click)="importSource()">Importar épocas</button></details>
 <label>Nombre de comparativa<input [(ngModel)]="name"></label><label>Referencia<select [(ngModel)]="referenceId" (ngModelChange)="result=null"><option value="">Elige</option><option *ngFor="let r of recordings" [value]="r.id">{{r.name}} · {{r.participant_id}} · {{r.stage_schema}}</option></select></label>
 <label *ngFor="let r of recordings"><input type="checkbox" [disabled]="r.id===referenceId||!r.device_id" [checked]="selected.includes(r.id)" (change)="toggle(r.id)">{{r.name}} · {{r.participant_id}} <a [href]="'/api/comparison-sleep/recordings/'+r.id" target="_blank" rel="noopener">Fuente y mapping</a></label><button *ngIf="recordings.length&&hasMore" (click)="loadMore()">Más grabaciones</button>
 <button [disabled]="!referenceId||!selected.length" (click)="calculate()">Comparar épocas</button><button [disabled]="!result" (click)="calculate(true)">Guardar snapshot</button></fieldset>
 <details *ngIf="saved.length"><summary>Comparativas de sueño guardadas</summary><p *ngFor="let s of saved"><input type="checkbox" [checked]="benchmarkIds.includes(s.id)" (change)="toggleBenchmark(s.id)"><button [disabled]="busy" (click)="open(s.id)">{{s.configuration.name}}</button></p><button [disabled]="busy||benchmarkIds.length<2" (click)="benchmark()">Benchmark de noches seleccionadas</button><p>Requiere night_id declarado en cada referencia. Una noche de cada participante/dispositivo cuenta una vez.</p></details>
 <section *ngIf="benchmarkResult as b"><h3>Benchmark por noche</h3><div class="table-wrap"><table><thead><tr><th>Dispositivo</th><th>n noches</th><th>Acuerdo medio %</th><th>Mediana %</th><th>SD %</th><th>IQR %</th><th>Kappa medio</th></tr></thead><tbody><tr *ngFor="let g of b.groups"><td>{{g.name}}</td><td>{{g.n_nights}}</td><td>{{number(g.metrics.agreement_percent.mean)}}</td><td>{{number(g.metrics.agreement_percent.median)}}</td><td>{{number(g.metrics.agreement_percent.sd)}}</td><td>{{number(g.metrics.agreement_percent.iqr)}}</td><td>{{number(g.metrics.kappa.mean)}}</td></tr></tbody></table></div><p *ngFor="let row of b.rows"><button (click)="open(row.comparison_id)">{{row.name}} · {{row.participant_id}} · {{row.night_id}} · {{number(row.metrics.agreement_percent)}} %</button></p><button (click)="downloadBenchmark()">Benchmark JSON</button></section>
 <ng-container *ngIf="result as r"><h3>{{r.configuration.name}}</h3><p>Referencia: {{r.reference_name}} · Calidad declarada: {{r.reference_quality||'desconocida'}}</p><button (click)="exportJson()">Evidencia JSON</button><button (click)="exportCsv()">Métricas por clase CSV</button>
 <article *ngFor="let row of r.rows"><h3>{{row.name}}</h3><p>{{row.metrics.n_epochs}} / {{row.metrics.expected_epochs}} épocas pareadas · Cobertura {{number(row.metrics.coverage_percent)}}% · Acuerdo {{number(row.metrics.agreement_percent)}}% · Kappa {{number(row.metrics.kappa)}}</p><p>{{row.metrics.reference_missing_or_unmapped}} épocas de referencia ausentes/sin mapping; {{row.metrics.device_missing_or_unmapped}} del dispositivo.</p>
 <div class="table-wrap"><table><caption>Matriz: filas de referencia, columnas de dispositivo</caption><thead><tr><th>Etapa</th><th *ngFor="let c of row.metrics.classes">{{c}}</th></tr></thead><tbody><tr *ngFor="let c of row.metrics.classes;let i=index"><th>{{c}}</th><td *ngFor="let n of row.metrics.confusion_matrix[i]">{{n}}</td></tr></tbody></table></div>
 <div class="table-wrap"><table><thead><tr><th>Clase</th><th>n referencia</th><th>n dispositivo</th><th>Precisión</th><th>Recall</th><th>F1</th></tr></thead><tbody><tr *ngFor="let c of row.metrics.per_class"><td>{{c.class}}</td><td>{{c.reference_n}}</td><td>{{c.device_n}}</td><td>{{number(c.precision)}}</td><td>{{number(c.recall)}}</td><td>{{number(c.f1)}}</td></tr></tbody></table></div></article>
 <p>Acuerdo y kappa son descriptivos de estas épocas; no se calculan intervalos suponiendo que cada época es un participante independiente.</p></ng-container></section>`,
 styles:[`.panel{padding:1rem;background:var(--surface);border:1px solid var(--line);border-radius:var(--r-md)}label{display:block;margin:.7rem 0}textarea{width:100%;font-family:monospace;background:var(--surface-2);color:var(--ink)}input,button,select{padding:.5rem;background:var(--surface);color:var(--ink);border:1px solid var(--line);margin:.3rem}fieldset{border:0;padding:0}table{border-collapse:collapse;width:100%}th,td{padding:.6rem;text-align:left;border-bottom:1px solid var(--line)}.table-wrap{overflow:auto}p{color:var(--ink-3)}`]})
export class ComparisonSleepComponent implements OnInit {
 @Input() devices:{id:string;name:string}[]=[];
 sourceJson=JSON.stringify({name:'',reference_label:'',participant_id:'',night_id:null,epoch_seconds:30,stage_schema:'FIVE_STAGE',mapping_version:'1',stage_map:{WAKE:'WAKE',N1:'N1',N2:'N2',N3:'N3',REM:'REM'},epochs:[]},null,2);
 deviceId='';name='Comparación de sueño';referenceId='';selected:string[]=[];recordings:any[]=[];saved:any[]=[];result:any=null;busy=false;message='';offset=0;hasMore=false;
 benchmarkIds:string[]=[];benchmarkResult:any=null;
 constructor(private http:HttpClient){}
 ngOnInit():void{this.loadMore();this.refreshSaved();}
 loadMore():void{this.http.get<any[]>('/api/comparison-sleep/recordings',{params:{offset:this.offset}}).subscribe({next:r=>{this.recordings=[...this.recordings,...r];this.offset+=r.length;this.hasMore=r.length===100;},error:e=>this.fail(e)});}
 refreshSaved():void{this.http.get<any[]>('/api/comparison-sleep/comparisons').subscribe({next:r=>this.saved=r,error:e=>this.fail(e)});}
 readFile(event:Event):void{const f=(event.target as HTMLInputElement).files?.[0];if(!f)return;if(f.size>5_000_000){this.message='El JSON supera 5 MB.';return;}const reader=new FileReader();reader.onload=()=>this.sourceJson=String(reader.result);reader.readAsText(f);}
 importSource():void{let body:any;try{body=JSON.parse(this.sourceJson);}catch{this.message='JSON inválido.';return;}this.busy=true;this.http.post('/api/comparison-sleep/recordings',{...body,device_id:this.deviceId||null}).subscribe({next:()=>{this.busy=false;this.message='Épocas importadas con su mapping.';this.offset=0;this.recordings=[];this.loadMore();},error:e=>this.fail(e)});}
 toggle(id:string):void{this.selected=this.selected.includes(id)?this.selected.filter(r=>r!==id):[...this.selected,id];this.result=null;}
 toggleBenchmark(id:string):void{this.benchmarkIds=this.benchmarkIds.includes(id)?this.benchmarkIds.filter(s=>s!==id):[...this.benchmarkIds,id];this.benchmarkResult=null;}
 benchmark():void{this.busy=true;this.http.post<any>('/api/comparison-sleep/benchmark',{comparison_ids:this.benchmarkIds}).subscribe({next:r=>{this.benchmarkResult=r;this.busy=false;},error:e=>this.fail(e)});}
 downloadBenchmark():void{this.download(JSON.stringify(this.benchmarkResult,null,2),'application/json','sueño-benchmark.json');}
 calculate(save=false):void{this.selected=this.selected.filter(id=>id!==this.referenceId);this.busy=true;this.message='';this.http.post<any>(`/api/comparison-sleep/${save?'comparisons':'preview'}`,{name:this.name,reference_id:this.referenceId,recording_ids:this.selected}).subscribe({next:r=>{this.result=r.result||r;this.busy=false;if(save)this.refreshSaved();},error:e=>this.fail(e)});}
 open(id:string):void{this.busy=true;this.http.get<any>(`/api/comparison-sleep/comparisons/${id}`).subscribe({next:r=>{this.result=r.result;this.name=r.result.configuration.name;this.referenceId=r.result.configuration.reference_id;this.selected=r.result.configuration.recording_ids;this.busy=false;},error:e=>this.fail(e)});}
 number(v:unknown):string{return typeof v==='number'&&Number.isFinite(v)?v.toLocaleString('es-ES',{maximumFractionDigits:3}):'NO DATA';}
 exportJson():void{this.download(JSON.stringify(this.result,null,2),'application/json','sueño-comparativa.json');}
 exportCsv():void{const cell=(v:unknown)=>{let s=String(v??'');if(typeof v==='string'&&/^[=+@\-\t\r]/.test(s))s="'"+s;return '"'+s.replace(/"/g,'""')+'"';};const lines=[['recording_id','name','class','reference_n','device_n','precision','recall','f1'].join(',')];for(const row of this.result.rows)for(const c of row.metrics.per_class)lines.push([row.recording_id,row.name,c.class,c.reference_n,c.device_n,c.precision,c.recall,c.f1].map(cell).join(','));this.download(lines.join('\r\n'),'text/csv;charset=utf-8','sueño-clases.csv');}
 download(data:string,type:string,name:string):void{const url=URL.createObjectURL(new Blob([data],{type}));const link=document.createElement('a');link.href=url;link.download=name;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 fail(e:any):void{this.busy=false;this.message=typeof e.error?.detail==='string'?e.error.detail:JSON.stringify(e.error?.detail||'No se pudo completar la operación.');}
}
